[package]
name = "rnGdbStub"
version = "0.0.1"
authors = ["mean00"]
edition = "2021"

[lib]
name = "rnGdbStub"
path = "lib/lib.rs"
crate-type = ["staticlib"] # Creates static lib


[dependencies]
gdbstub = { path = "gdbstub", default-features = false }
gdbstub_arch = { path = "gdbstub/gdbstub_arch", default-features = false }

#libc = { version = "0.2", default-features = false }
#log = { version = "0.4", features = ["release_max_level_off"] }

[profile.dev]
panic = "abort"
lto = true
codegen-units = 1
debug = true

[profile.release]
panic = "abort"
opt-level = 's'  # Optimize for size.
lto = true
codegen-units = 1
debug = true
